---

- name: Cow Say playbook
  hosts: all
  tasks:

  - name: Install cowsay
    apt:
      name: cowsay
      state: present
    become: yes
  
  - name: Say MOO
    command:
      cmd: cowsay "MOO!!"
    register: out

  - debug:
      msg: "{{out.stdout_lines}}"